CREATE TABLE dim_sales_teams (
    -- Surrogate key
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 30000001) PRIMARY KEY,

    -- Business / natural key
    sales_agent TEXT NOT NULL UNIQUE,

    -- Other columns
    manager TEXT,
    regional_office TEXT
);