CREATE TABLE dim_accounts (
    -- Surrogate key
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY,

    -- Business / natural key (from CSV)
    account TEXT NOT NULL UNIQUE,

    -- Other columns
    sector TEXT,
    year_established INTEGER,
    revenue NUMERIC(18,2),
    employees INTEGER,
    office_location TEXT,
    subsidiary_of TEXT
);