CREATE TABLE dim_products (
    -- Surrogate key
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 20000001) PRIMARY KEY,

    -- Business / natural key
    product TEXT NOT NULL UNIQUE,

    -- Other columns
    series TEXT,
    sales_price NUMERIC(18,2)
);